#
# Copyright (c) 2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build HTML preview of PR

on:
  pull_request:
    branches: ['*']

jobs:
  adoc_build:
    name: Asciidoctor Build For PR branch preview
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup environment
      run: |
        # update
        sudo apt-get update -y || true
        # install 
        sudo apt-get -y -q install asciidoctor && asciidoctor --version

    - name: Build guides and index
      run: |
        mkdir -p titles-generated/; 
        echo "<html><head><title>Red Hat Developer Hub Documentation Preview</title></head><body><ul>" > titles-generated/index.html;
        for t in $(find titles -name master.adoc | sort -uV); do
          d=${t%/*}; d=${d/titles/titles-generated}; 
          echo "Building $t into $d ..."; 
          asciidoctor --destination-dir $d --backend=html5 -o index.html $t; ls -la $d;
          echo "<li><a href=${d/titles-generated/.}>${d/titles-generated\//}</a></li>" >> titles-generated/index.html;
        done
        echo "</ul></body></html>" >> titles-generated/index.html

    # repo must be public for this to work
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.RHDH_BOT_TOKEN }}
        publish_branch: pr-${{ github.event.pull_request.number }}
        publish_dir: ./titles-generated

    - name: "Use Node 18"
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: PR comment with doc preview
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.RHDH_BOT_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'PR Preview: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/tree/pr-${{ github.event.pull_request.number }}' 
          });
