---
name: Verify style guide compliance on pull request
on: [pull_request]

jobs:
  vale:
    name: Linting with Vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      - name: Run Vale on new and modified content
        uses: errata-ai/vale-action@v2
        with:
          files: assemblies
          filter_mode: diff_context
          vale_flags: "--no-exit --minAlertLevel=error"
          reporter: github-pr-review
          token: ${{ secrets.RHDH_BOT_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.RHDH_BOT_TOKEN }}
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.RHDH_BOT_TOKEN }}
